(function(){
    var config = {
        paths: {
            'text': 'bower_components/requirejs-text/text',
            'jquery': 'bower_components/jquery/jquery.min',
            'angular': 'bower_components/angular/angular',
            'ngRoute' : 'bower_components/angular-route/angular-route',
            'angularCookies': 'bower_components/angular-cookies/angular-cookies.min',
            'angularUIStates': 'bower_components/angular-ui-router/release/angular-ui-router.min',
            'angularUIUtils': 'bower_components/ichuan-bower-angular-ui-utils/ui-utils.min',
            'angularUIGrid': 'bower_components/ng-grid-bower/ng-grid.min',
            'angularSanitize': 'bower_components/angular-sanitize/angular-sanitize.min',
            'lodash' : 'bower_components/lodash/dist/lodash.compat.min',
            'bootstrap': 'bower_components/bootstrap/dist/js/bootstrap.min',
            'angularUIBootstrap': 'bower_components/angular-ui-bootstrap-bower/ui-bootstrap-tpls',
            'uiBootstrapOverrides': 'modules/extensions/angular-ui-bootstrap/templates/ui-bootstrap-overrides',
            'restangular': 'bower_components/restangular/dist/restangular.min',
            'messagingServices': 'bower_components/messaging-services/messaging-services.min',
            'polyfills': 'bower_components/polyfills/polyfills',
            'jscrollpane': 'bower_components/jscrollpane/jquery.jscrollpane.min',
            'es5-shim': 'bower_components/es5-shim/es5-shim.min',
            'details-shim': 'bower_components/details-shim/details-shim',
            'openLayers' : 'bower_components/open-layers/open-layers.min',
            'openLayersAnimatedCluster': 'bower_components/open-layers/open-layers-animated-cluster.min',
            'javascript-util' : 'bower_components/jsts/bower_components/javascript.util',
            'jsts' : 'bower_components/jsts/bower_components/jsts',

            'moment': 'bower_components/momentjs/min/moment.min',
            'moment-timezone': 'bower_components/moment-timezone/min/moment-timezone.min',
            'moment-timezone-data': 'bower_components/moment-timezone/moment-timezone-data',
            'capd-moment' : 'utils-amd/bower_components-wrappers/capdMoment',

            'angulartics': 'bower_components/angulartics/dist/angulartics.min',
            'angulartics-ga': 'bower_components/angulartics/dist/angulartics-ga.min',
            'jquery-placeholder': 'bower_components/jquery-html5-placeholder-shim/jquery.html5-placeholder-shim',
            'angular-placeholder': 'bower_components/angular-placeholder-shim/angular-placeholder-shim.min',
            'proj4': 'bower_components/proj4/proj4js-compressed',
            'projectionEPSG27700':'bower_components/proj4/defs/EPSG27700',
            'OsGridRef':'bower_components/os-grid/OsGridRef.min',
            'sopraTrace': 'bower_components/sopra-trace/Trace.min',
            'sopraSnapping': 'bower_components/sopra-snapping/FixedSnapping.min',
            'bowser': 'bower_components/bowser/bowser.min',
            'modernizr' : 'bower_components/modernizr-custom/modernizr.custom.77028',
            'sopraFeatureToolsUtils': 'bower_components/sopra-feature-tools/Utils.min',
            'sopraFeatureTools': 'bower_components/sopra-feature-tools/MathFeatureTools.min',
            'details-polyfill' : 'bower_components/details-polyfill/details.polyfill'
        },
        shim: {
            'jscrollpane': ['jquery'],
            'angular': {'deps': ['jquery'], 'exports': 'angular'},
            'angularUIStates': ['angular'],
            'angularUIUtils': ['angular'],
            'angularUIGrid': ['angular'],
            'angularCookies': ['angular'],
            'angularSanitize': ['angular'],
            'bootstrap': ['jquery'],
            'angularUIBootstrap':  ['angular', 'bootstrap'],
            'uiBootstrapOverrides': ['angularUIBootstrap'],
            'openLayers': {'exports': 'OpenLayers'},
            'openLayersAnimatedCluster': ['openLayers'],
            'jsts': {'deps': ['openLayers', 'javascript-util'], 'exports': 'jsts'},
            'sopraSnapping': ['openLayers'],
            'sopraTrace': ['openLayers', 'sopraSnapping'],
            'sopraFeatureToolsUtils': ['openLayers'],
            'sopraFeatureTools': ['openLayers', 'sopraFeatureToolsUtils'],
            'restangular': ['angular', 'lodash'],
            'messagingServices': ['angular', 'jquery'],
            'angulartics': ['angular'],
            'angulartics-ga': ['angulartics'],
            'jquery-placeholder': ['jquery'],
            'angular-placeholder': ['angular', 'jquery-placeholder'],
            'projectionEPSG27700': ['proj4'],
            'OsGridRef' : {'exports' : 'OsGridRef'},
            'ngRoute' : ['angular']
        },
        priority: ['polyfills', 'modernizr', 'angular'],
        //momentjs configuration
        noGlobal: true
    };

    require.config(config);
})()